### ISSUE TITLE
Please update plugin.info.txt

### ISSUE THREAD

**Issue by moisesbr-dw** [samfisch/dokuwiki-plugin-forcessllogin#14]
@samfisch please update plugin.info.txt with a new date, in order to allow automatic updates.

**Comment by samfisch** [comment]
Excerpts from Moisés Braga Ribeiro's message of 2020-06-15 13:12:25 -0700:
> @samfisch please update plugin.info.txt with a new date, in order to allow automatic updates.

sorry, could have thaught about that myself. Thanks for your effort,
keep on hacking :)

**Comment by moisesbr-dw** [comment]
Thank you!
