### ISSUE TITLE
It´s not possible to update to newest version inside DokuWiki

### ISSUE THREAD

**Issue by alexhaller** [samfisch/dokuwiki-plugin-forcessllogin#3]
Hi Sam,

inside DokuWiki it´s not possible to update to the newest version which fixes the wrong base url error.
The date mentioned by DokuWiki (https://www.dokuwiki.org/plugin:forcessllogin) isn´t also correct.
Can you fix that?

Thx a lot!

Best regards,
Alex

**Comment by samfisch** [comment]
this should be fixed now
